// <auto-generated />
using System;
using LiveFuelMap.DAL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiveFuelMap.DAL.Persistence.Migrations
{
    [DbContext(typeof(LiveFuelMapDbContext))]
    [Migration("20260427212606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RevokedAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("api_tokens", (string)null);
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.ApplicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Exception")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "CreatedAt");

                    b.ToTable("application_logs", (string)null);
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int?>("FuelId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuelId");

                    b.HasIndex("StationId");

                    b.HasIndex("UserId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("data_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = true,
                            Name = "Minfin Kharkiv",
                            Type = "Html",
                            Url = "https://index.minfin.com.ua/ua/markets/fuel/reg/harkovskaya/"
                        },
                        new
                        {
                            Id = 2,
                            Enabled = false,
                            Name = "Open Fuel JSON",
                            Type = "Json",
                            Url = "https://example.com/fuel-prices.json"
                        });
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("fuels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "a95plus",
                            Name = "? 95+",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "a95",
                            Name = "? 95",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "a92",
                            Name = "? 92",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "diesel",
                            Name = "??",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "gas",
                            Name = "???",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.FuelPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsManual")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Popularity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("FuelId", "Date");

                    b.HasIndex("StationId", "FuelId", "Date")
                        .IsUnique();

                    b.ToTable("fuel_prices", (string)null);
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.ParserRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecordsFound")
                        .HasColumnType("int");

                    b.Property<int>("RecordsSaved")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "StartedAt");

                    b.ToTable("parser_runs", (string)null);
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("NormalizedKey", "City")
                        .IsUnique();

                    b.ToTable("stations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "???????? ?????? ???????, 142A",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 49.966850m,
                            Longitude = 36.317010m,
                            Name = "AMIC",
                            NormalizedKey = "amic"
                        },
                        new
                        {
                            Id = 2,
                            Address = "?????? ???????? ?????????, 85",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 50.012210m,
                            Longitude = 36.255580m,
                            Name = "Marshal",
                            NormalizedKey = "marshal"
                        },
                        new
                        {
                            Id = 3,
                            Address = "?????? ???????????, 98?",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 50.005090m,
                            Longitude = 36.218900m,
                            Name = "Ovis",
                            NormalizedKey = "ovis"
                        },
                        new
                        {
                            Id = 4,
                            Address = "????????????? ????????, 223",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 49.884170m,
                            Longitude = 36.291900m,
                            Name = "Rodnik",
                            NormalizedKey = "rodnik"
                        },
                        new
                        {
                            Id = 5,
                            Address = "?????? ?????????",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 49.947570m,
                            Longitude = 36.186600m,
                            Name = "SUN OIL",
                            NormalizedKey = "sun-oil"
                        },
                        new
                        {
                            Id = 6,
                            Address = "???????? ????? ??????????",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 49.945000m,
                            Longitude = 36.313130m,
                            Name = "Shell",
                            NormalizedKey = "shell"
                        },
                        new
                        {
                            Id = 7,
                            Address = "????????????? ????????, 127?",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 49.964610m,
                            Longitude = 36.259940m,
                            Name = "U.GO",
                            NormalizedKey = "ugo"
                        },
                        new
                        {
                            Id = 8,
                            Address = "?????? ????????, 41",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 49.996090m,
                            Longitude = 36.250020m,
                            Name = "WOG",
                            NormalizedKey = "wog"
                        },
                        new
                        {
                            Id = 9,
                            Address = "???????? ???????",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 49.945400m,
                            Longitude = 36.332170m,
                            Name = "?????",
                            NormalizedKey = "avias"
                        },
                        new
                        {
                            Id = 10,
                            Address = "?????? ??????????????, 2?",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 50.021000m,
                            Longitude = 36.319070m,
                            Name = "????-?????",
                            NormalizedKey = "brsm-nafta"
                        },
                        new
                        {
                            Id = 11,
                            Address = "?????? ???????????, 44",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 49.997310m,
                            Longitude = 36.227570m,
                            Name = "????",
                            NormalizedKey = "okko"
                        },
                        new
                        {
                            Id = 12,
                            Address = "?????? ????????? ???????",
                            City = "??????",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-station.jpg",
                            IsActive = true,
                            Latitude = 49.989690m,
                            Longitude = 36.287720m,
                            Name = "????????",
                            NormalizedKey = "ukrnafta"
                        });
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuelId");

                    b.HasIndex("UserId", "FuelId", "City", "Frequency")
                        .IsUnique();

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailConfirmationTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.ApiToken", b =>
                {
                    b.HasOne("LiveFuelMap.DAL.Entities.User", "CreatedByUser")
                        .WithMany("CreatedApiTokens")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.Comment", b =>
                {
                    b.HasOne("LiveFuelMap.DAL.Entities.Fuel", "Fuel")
                        .WithMany("Comments")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LiveFuelMap.DAL.Entities.Station", "Station")
                        .WithMany("Comments")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiveFuelMap.DAL.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.FuelPrice", b =>
                {
                    b.HasOne("LiveFuelMap.DAL.Entities.Fuel", "Fuel")
                        .WithMany("FuelPrices")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiveFuelMap.DAL.Entities.DataSource", "Source")
                        .WithMany("FuelPrices")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LiveFuelMap.DAL.Entities.Station", "Station")
                        .WithMany("FuelPrices")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");

                    b.Navigation("Source");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.ParserRun", b =>
                {
                    b.HasOne("LiveFuelMap.DAL.Entities.DataSource", "Source")
                        .WithMany("ParserRuns")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.Subscription", b =>
                {
                    b.HasOne("LiveFuelMap.DAL.Entities.Fuel", "Fuel")
                        .WithMany("Subscriptions")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiveFuelMap.DAL.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.DataSource", b =>
                {
                    b.Navigation("FuelPrices");

                    b.Navigation("ParserRuns");
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.Fuel", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FuelPrices");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.Station", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FuelPrices");
                });

            modelBuilder.Entity("LiveFuelMap.DAL.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CreatedApiTokens");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
